### ISSUE TITLE
include graphs of the membership functions [enhancement]: 

### ISSUE THREAD

**Issue by JeffreySarnoff** [lucaferranti/FuzzyLogic.jl#3]
## Feature description
In the future docs, include graphs of the membership functions, both separately and overlaid in related groups.
(for the separately graphed membership functions, perhaps an alongside copy with a lighter gray curve tracking the derivative of each membership function).

**Comment by lucaferranti** [comment]
This is indeed a very nice idea.

For the separated membership functions, in #4 the MFs documentation page has a plot associated to each docstring. As a nice bonus, that page is automatically generated, no manual work needed to arrange docstrings and plots. (Github actions seems to have some issues that lead the preview deployment to time out, but it should be available sooner or later)

I am not sure about having the derivative on the same plot. The membership function itself is between 0 and 1, but the derivative in principle could be arbitrary big, e.g. if the function has a quick transition from 0 to 1), in which case plotting both on the same graph could "hide" the original MF.

I am not sure I get what you mean by plotting the membership functions in related groups. Do you mean to plot all MFs associated to the same variable on the same plot? That is actually already supported, see e.g. [here](https://www.lucaferranti.com/FuzzyLogic.jl/dev/tutorials/mamdani/#Visualization).

Also, although not documented yet, membership functions are actually exported and have their own plotting recipe, for example the following works:

```julia
using FuzzyLogic, Plots
mf = TriangularMF(1, 2, 3)
plot(mf, 0, 4)
```

**Comment by lucaferranti** [comment]
the documentation has now automatically generated plots of each membership function, I dont see a compelling need for having the derivative on the same plot, but that could be added easily. I guess having the derivative could be more interesting once the library has more mature functionalities for learning inference systems from data. Closing for now, but happy to reopen if more comments/suggestions come up.
